name: technician_time_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: 3.0.10
  dio_http_cache: ^0.2.11
  dio_cookie_manager: ^1.0.0  #latest version
  pretty_dio_logger: ^1.1.1
  flutter_secure_storage: 3.3.5
  background_fetch: ^1.0.1
  sqflite:

  connectivity: 2.0.2
  map_launcher: ^2.1.1
  image_picker: ^0.6.7+22
  video_player: ^1.0.1
  camerawesome: ^0.2.1+3
  camera: ^0.7.0+2
  path_provider: ^1.6.27
  photo_view: ^0.10.3
  cached_network_image: ^2.5.0
  intl: ^0.16.1
  gallery_saver: ^2.0.3
  collection: ^1.14.13
  grouped_list: ^3.7.1
  flutter_libphonenumber: ^1.0.3
  url_launcher: ^6.0.2
  dropdown_search: ^0.4.9
  recase: ^3.0.1
  fluttertoast:
  pull_to_refresh: ^2.0.0
  geocoder:
  google_sign_in: 4.5.6
  google_maps_flutter:
  permission_handler: 5.1.0+2
  geolocator:
  jwt_decoder: ^2.0.1
  material_floating_search_bar: ^0.3.4
  http:
  ota_update: 3.1.0

  #state management
  flutter_bloc: ^7.1.0

  #Utility
  equatable: ^2.0.3
  shared_preferences:


    #  flutter_svg: # only if you want to use icons as they are svgs


    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
  package_info_plus: ^0.5.0
  after_layout: ^1.1.0
  sortedmap: ^0.4.2+1
  clipboard: ^0.1.3
  flutter_latlong: ^1.0.3
  rollbar_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
